#!/bin/bash


SECRET_FILE=docker_secret.txt

if [ -f "$SECRET_FILE" ]; then
    echo "$SECRET_FILE exist"
    source docker_secret.txt
    echo ${docker_username}
    echo ${docker_email}
else 
    echo "$FILE does not exist"
    exit 1
fi

if [ -z "${docker_username}" ]
then
      echo "\$docker_username is empty"
      exit 1
else
      echo "\$docker_username is NOT empty"
fi

if [ -z "${docker_password}" ]
then
      echo "\$docker_password is empty"
      exit 1
else
      echo "\$docker_password is NOT empty"
fi

if [ -z "${docker_email}" ]
then
      echo "\$docker_password is empty"
      exit 1
else
      echo "\$docker_password is NOT empty"
fi

echo " ====== all clear to proceed with deployment ====="


for i in elasticsearch  spark-operator kafka zookeeper 
do

kubectl create namespace $i
sleep 3
kubectl create secret docker-registry vinod-docker-hub-secret \
--docker-server="https://index.docker.io/v1/" \
--docker-username="${docker_username}" \
--docker-password="${docker_password}" \
--docker-email="${docker_email}" \
-n $i
done
